Add i3 workspace rename script with persistent workspace number
This commit adds a script that allows renaming of the current or a
specified workspace without changing the current workspace number/id
except when its explicitly given in the new name.

This allows renaming of the workspace without breaking the shortcuts for it.
For example the workspace '3: test' should be renamed to 'mail',
the result would be '3: mail'.  The shortcuts still work as the workspace
number hasn't been changed.

Additionally it allows moving of workspaces by giving a workspace number
in the name explicitly
For example: '3: test' renamed to '6: mail' will work as expected

diff --git a/private_dot_local/bin/executable_screenshot b/private_dot_local/bin/executable_screenshot
--- a/private_dot_local/bin/executable_screenshot
+++ b/private_dot_local/bin/executable_screenshot
@@ -8,6 +8,13 @@
 # All screenshots are saved under ~/Pictures/ with the file name screenshot-$(date).png
 # and are copied automatically to the clipboard
 
+show_help()
+{
+	echo "$(basename "${0}"): take a screenshot of current desktop"
+	printf "  -h\t show this help\n"
+	printf "  -s\t screenshot a rectangular area\n"
+}
+
 to_clipboard()
 {
 	if command -v xclip 1>/dev/null 2>&1; then
@@ -59,20 +66,13 @@ take_screenshot()
 	fi
 }
 
-show_help()
-{
-	echo "$(basename "${0}"): take a screenshot of current desktop"
-	printf "  -h\t show this help\n"
-	printf "  -s\t screenshot a rectangular area\n"
-}
-
-filepath="$HOME/Pictures/screenshot-$(date +%F@%H'%M'%S%z).png"
+filepath="${HOME}/Pictures/screenshot-$(date +%F@%H'%M'%S%z).png"
 
 while getopts 'sh' opt; do
 	case "${opt}" in
 		s ) selection=1 ;;
 		h ) show_help; exit ;;
-		* ) echo "Error: use -h to show help" 1>&2; exit 1 ;;
+		* ) echo "Error: use -h for help" 1>&2; exit 1 ;;
 	esac
 done
 
