Check for jq and alts availability for i3-workspace-rename
This commit adds a simple dependency check if running
i3-workspace-rename.
jq and derivates (gojq) are required to retrieve all workspace names
from i3.
Without it i3-workspace-rename cannot work and therefore we'll abort if
they are missing

diff --git a/private_dot_local/bin/executable_i3-workspace-rename b/private_dot_local/bin/executable_i3-workspace-rename
--- a/private_dot_local/bin/executable_i3-workspace-rename
+++ b/private_dot_local/bin/executable_i3-workspace-rename
@@ -29,12 +29,15 @@ script_path()
 
 select_jq()
 {
-	# Try `gojq` first, normally installed by chezmoi
+	# Try `gojq` first, can added as static binary easily
 	if command -v gojq 1>/dev/null 2>&1; then
 		cmd_jq="gojq --raw-output"
-	# Try `jq` as fallback, must be installed by system
+	# Try `jq` as fallback, easiest installable by system package manager
 	elif command -v jq 1>/dev/null 2>&1; then
 		cmd_jq="jq -r"
+	else
+		echo "Error: cannot find jq or gojq" 1>&2
+		exit 1
 	fi
 }
 
