Move user bin to more common ~/.bin directory
The ~/.local/bin has been moved to ~/.bin to make it the same level as
~/.config, ~/.cache, ~/.var, etc.

Also 'termfg' has been improved to fail if no command has been provided
and the commands substitution is now done in the terminal emulators shell,
and not in 'termfg', this should fix potential issues with environment
differences between the calling process and the environment where the terminal
emulator is being run

diff --git a/dot_bin/executable_termfg b/dot_bin/executable_termfg
--- a/dot_bin/executable_termfg
+++ b/dot_bin/executable_termfg
@@ -8,13 +8,18 @@
 #
 # Note: i3-sensible-terminal provides similar functionaliy but without waiting for termination of the terminal.
 
+if [ -z "${*}" ]; then
+	echo "Error: no command provided" 1>&2
+	exit 1
+fi	
+
 if command -v xfce4-terminal 1>/dev/null 2>&1; then
-	exec xfce4-terminal --disable-server --command "${@}"
+	exec xfce4-terminal --disable-server --execute /usr/bin/env sh -c "${*}"
 elif command -v lxterminal 1>/dev/null 2>&1; then
-	exec lxterminal --command "${@}"
+	exec lxterminal --command /usr/bin/env sh -c "${*}"
 elif command -v gnome-terminal 1>/dev/null 2>&1; then
-	exec gnome-terminal --wait -- env sh -c "${@}"
+	exec gnome-terminal --wait -- /usr/bin/env sh -c "${*}"
 else
-	echo "No supported terminal emulator found!" 1>&2
+	echo "Error: No supported terminal emulator found!" 1>&2
 	exit 1
 fi
