Add usersuspend and usershutdown scripts
These scripts allow the user to shutdown/suspend/hibernate the computer
without requiring root rights.
Well these scripts try to make this possible by trying every options
until one succeeds.
In most cases the administrator still needs to setup something like
sudoers file or setuid for shutdown to work

diff --git a/private_dot_bin/executable_usershutdown b/private_dot_bin/executable_usershutdown
--- a/private_dot_bin/executable_usershutdown
+++ b/private_dot_bin/executable_usershutdown
@@ -1,2 +1,14 @@
 #! /usr/bin/env sh
+
+# This script is a wrapper that tries to allow the user to shutdown the
+# machine without root rights.
+# In most cases the administrator must manually change settings 
+# (e.g. the sudoers file) to allow unprivileged users to shutdown the system
+
+if shutdown -P now -h -a 2>/dev/null; then :
+elif poweroff -p 2>/dev/null; then :
+elif systemctl poweroff 2>/dev/null; then :
+else echo "Error: failed to shutdown the machine" 1>&2; exit 1
+fi	
+
 # vim: filetype=sh
