Allow target arguments to pwrsuspend and pwrshutdown scripts
This commit allows the user to specify the desired target for the
pwrshutdown and the pwrsuspend scripts.
Also pwrshutdown gained the reboot action.

`pwrshutdown` supports two modes:
- shutdown (default) (param: shutdown)
- reboot             (param: reboot)

`pwrsuspend` supports now three modes:
- hibernate only     (param: hibernate)
- suspend only       (param: suspend)
- try hibernate, then suspend (default)

The previous behavior is unchanged when invoked without arguments.
(See default above)

Additionally the scripts will now log their output to `~/.var/log/`
when the directory exists, if not the log is written to the console.

Also pwrshutdown has now dbus commands it can try to shutdown or reboot
the machine. This is only useable for DE with dbus support. However that
should provide passwordless shutdown/reboot when allowed.

The dbus commands are now tried first in both pwrshutdown and pwrsuspend,
as they mimick the action of DE's shutdown dialog most closest

diff --git a/private_dot_bin/executable_pwrshutdown b/private_dot_bin/executable_pwrshutdown
--- a/private_dot_bin/executable_pwrshutdown
+++ b/private_dot_bin/executable_pwrshutdown
@@ -4,11 +4,48 @@
 # machine without root rights.
 # In most cases the administrator must manually change settings 
 # (e.g. the sudoers file) to allow unprivileged users to shutdown the system
+# The user can add the desired state as argument (`shutdown` to poweroff,
+# `reboot` to reboot the system)
+# Last script output is being written to ~/.var/log/pwrshutdown.log
 
-if shutdown -P now -h -a 2>/dev/null; then :
-elif poweroff -p 2>/dev/null; then :
-elif systemctl poweroff 2>/dev/null; then :
-else echo "Error: failed to shutdown the machine" 1>&2; exit 1
-fi	
+if [ -d "${HOME}/.var/log" ]; then
+	exec 1>"${HOME}/.var/log/pwrshutdown.log" 2>&1
+fi
+
+action="${1}"
+
+shutdown()
+{
+	dbus-send --system --print-reply --dest="org.freedesktop.login1" \
+			/org/freedesktop/login1 \
+			org.freedesktop.login1.Manager.PowerOff \
+			boolean:true || \
+	shutdown -P now -h -a || \
+	poweroff -p || \
+	systemctl poweroff || \
+	return 1
+}
+
+reboot()
+{
+	dbus-send --system --print-reply --dest="org.freedesktop.login1" \
+			/org/freedesktop/login1 \
+			org.freedesktop.login1.Manager.Reboot \
+			boolean:true || \
+	shutdown -r now -a || \
+	reboot || \
+	systemctl reboot || \
+	return 1
+}
+
+case "${action}" in
+	r* )
+		reboot || { echo "Error: cannot reboot the system"; exit 1; } 1>&2
+		;;
+	s* | * )
+		shutdown || { echo "Error: cannot shutdown the system"; exit 1; } 1>&2
+		;;
+esac
+
 
 # vim: filetype=sh
diff --git a/private_dot_bin/executable_pwrsuspend b/private_dot_bin/executable_pwrsuspend
--- a/private_dot_bin/executable_pwrsuspend
+++ b/private_dot_bin/executable_pwrsuspend
@@ -4,48 +4,60 @@
 # the machine without root rights.
 # In most cases the administrator must manually change settings 
 # (e.g. the sudoers file) to allow unprivileged users to hibernate the system.
-# Hibernation is preferred over suspending
+# Hibernation is preferred over suspending, alternatively the user can add
+# the desired state as argument (`suspend` to suspend,
+# `hibernate` to hibernate)
+# Last script output is being written to ~/.var/log/pwrsuspend.log
+
+if [ -d "${HOME}/.var/log" ]; then
+	exec 1>/"${HOME}/.var/log/pwrsuspend.log" 2>&1
+fi
+
+echo STDERR 1>&2
+echo STDOUT
+
+action="${1}"
 
 hibernate() {
-	if loginctl hybrid-sleep 2>/dev/null; then
-		return 1
-	elif s2both 2>/dev/null; then
-		return 1
-	elif systemctl hybrid-sleep 2>/dev/null; then
-		return 1
-	elif dbus-send --system --print-reply --dest="org.freedesktop.login1" \
-			/org/freedesktop/login1 org.freedesktop.login1.Manager.Hibernate \
-			boolean:true 2>/dev/null 1>&2; then
-		return 1
-	elif loginctl hibernate 2>/dev/null; then
-		return 1
-	elif s2disk 2>/dev/null; then
-		return 1
-	elif systemctl hibernate 2>/dev/null; then
-		return 1
-	fi
+	dbus-send --system --print-reply --dest="org.freedesktop.login1" \
+			/org/freedesktop/login1 \
+			org.freedesktop.login1.Manager.HybridSleep \
+			boolean:true || \
+	loginctl hybrid-sleep 2>/dev/null || \
+	s2both || \
+	systemctl hybrid-sleep || \
+	dbus-send --system --print-reply --dest="org.freedesktop.login1" \
+			/org/freedesktop/login1 \
+			org.freedesktop.login1.Manager.Hibernate \
+			boolean:true || \
+	loginctl hibernate || \
+	s2disk || \
+	systemctl hibernate || \
+	return 1
 }
 
-fallbacksuspend() {
-	if loginctl suspend-then-hibernate 2>/dev/null; then
-		return 1
-	elif dbus-send --system --print-reply --dest="org.freedesktop.login1" \
-			/org/freedesktop/login1 org.freedesktop.login1.Manager.Suspend \
-			boolean:true 2>/dev/null 1>&2; then
-		return 1
-	elif loginctl suspend 2>/dev/null; then
-		return 1
-	elif s2ram 2>/dev/null; then
-		return 1
-	elif systemctl suspend 2>/dev/null; then
-		return 1
-	fi
+suspend() {
+	dbus-send --system --print-reply --dest="org.freedesktop.login1" \
+			/org/freedesktop/login1 \
+			org.freedesktop.login1.Manager.Suspend \
+			boolean:true || \
+	loginctl suspend-then-hibernate 2>/dev/null || \
+	systemctl suspend-then-hibernate || \
+	loginctl suspend || \
+	s2ram || \
+	systemctl suspend || \
+	return 1
 }
 
-if ! hibernate; then :
-elif ! fallbacksuspend; then :
-else echo "Error: failed to shutdown the machine" 1>&2; exit 1
-fi	
-
+case "${action}" in
+	s* )
+		suspend || { echo "Error: failed to suspend the system"; exit 1; } 1>&2
+		;;
+	h* )
+		hibernate || { echo "Error: failed to hibernate the system"; exit 1; } 1>&2
+		;;
+	* )
+		hibernate || suspend || { echo "Error: failed to set the system to sleep"; exit 1; } 1>&2
+esac
 
 # vim: filetype=sh
