Switch between Selenized colorschemes with chezmoi
This commit adds the ability to switch between Selenized colorschemes by
simply running `chezmoi init --apply`. The user will be asked what theme
he wants to select. Available are only Selenized colorschemes:
- black
- white
- dark
- light

Those will be applied to i3, rofi and dunst.
On applying i3 and dunst will be reloaded to immediately reflect the
changes; Vim and Tmux configurations are currently not added to this repo
therefore those won't have the colorscheme applied.

Further things I could add: xfce-terminal themes

diff --git a/private_dot_config/i3/run_after_i3_init.sh.tmpl b/private_dot_config/i3/run_after_i3_init.sh.tmpl
--- a/private_dot_config/i3/run_after_i3_init.sh.tmpl
+++ b/private_dot_config/i3/run_after_i3_init.sh.tmpl
@@ -84,8 +84,24 @@ check_primary()
 	fi
 }
 
+reload()
+{
+	if [ -n "${I3SOCK}" ]; then
+		if [ -f "${I3SOCK}" ]; then
+			i3-msg --socket "${I3SOCK}" reload
+		else
+			for socket in $(dirname ${I3SOCK})/ipc-socket.*; do
+				i3-msg --socket "${socket}" reload 1>/dev/null 2>&1
+			done
+		fi
+	else
+		echo "Warning: cannot reload i3: I3SOCK env not found" 1>&2
+	fi
+}
+
 verify_deps
 check_primary
+reload
 
 {{ end }}
 
